#!/bin/bash

docker build \
    --build-arg CMDLINE_TOOLS_VERSION=$CMDLINE_TOOLS_VERSION \
    --build-arg OPENJDK_VERSION=$OPENJDK_VERSION \
    --build-arg BUILD_TOOLS=$BUILD_TOOLS \
    --build-arg TARGET_SDK=$TARGET_SDK \
    --build-arg ANDROID_HOME=$ANDROID_HOME \
    --build-arg RUBY_VERSION=$RUBY_VERSION \
    --build-arg FASTLANE_VERSION=$FASTLANE_VERSION \
    -f $DOCKERFILE_PATH -t $IMAGE_NAME .
